# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Show tasks
    cmds:
      - task -a
    silent: true

  setup-game:
    desc: Setup elixir phoenix poker game
    cmds:
      - mix phx.gen.live Games Game games title:string pot:integer
